name: cm_pytorch
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision
  - pytorch-cuda=11.8
  - pip
  - pip:
    - mpi4py
    - blobfile
    - pillow
    - numpy
    - scipy
    - tqdm
    - piq  # For LPIPS loss
